#!/usr/bin/env bash

case "$(printf "kill\nzzz\nupdate\nreboot\nshutdown" | dmenu -i -c -l 5)" in
	kill) ps -u "$USER" -o pid,comm,%cpu,%mem | dmenu -i -c -l 10 -p Kill: | awk '{print $1}' | xargs -r kill ;;
	zzz) slock systemctl suspend -i ;;
	update) (st -e sudo -v && nohup $(which updater)) & ;;
	reboot) systemctl reboot -i ;;
	shutdown) shutdown now ;;
	*) exit 1 ;;
esac
